# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(APP_SECRET)%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path:  "%kernel.project_dir%/var/sessions/%kernel.environment%"
        cookie_lifetime: 604800 # 1 week
    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
