filter:
    excluded_paths:
        - 'var/*'
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'vendor/*'
        - 'app/Resources/assets/vendor/*'
        - '*.min.js'
build:
    project_setup:
        before:
            - composer self-update
            - ./node_modules/.bin/encore production
    tests:
        override:
            -
                # Make sure nothing's changed in Git, which would indicate asset changes were not committed.
                command: git status | grep 'nothing to commit, working tree clean'
            -
                command: composer test
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
