build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                environment:
                    php:
                        version: 7.2
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    excluded_paths:
        - 'var/*'
        - 'tests/*'
        - 'bin/*'
    dependency_paths:
        - 'vendor/*'
        - 'assets/vendor/*'
        - '*.min.js'

