build:
    image: default-bionic
    environment:
        php: 8.1
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    excluded_paths:
        - 'var/*'
        - 'tests/*'
        - 'bin/*'
    dependency_paths:
        - 'vendor/*'
        - 'assets/vendor/*'
        - '*.min.js'

