filter:
    excluded_paths:
        - 'var/*'
        - 'tests/*'
        - 'bin/*'
        - 'vendor/*'
        - 'assets/vendor/*'
        - '*.min.js'
build:
    tests:
        override:

    nodes:
        tests:
            environment:
                php:
                    version: 7.2
