filter:
    excluded_paths:
        - 'var/*'
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'vendor/*'
        - 'app/Resources/assets/vendor/*'
        - '*.min.js'
build:
    project_setup:
        before:
            - composer self-update
            - ./node_modules/.bin/encore production
    tests:
        override:
            -
                command: composer test
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
