# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.2

# optionally specify a list of environments, for example to test different RDBMS
env:
  - IS_LABS=0

install:
  - composer install
  - 'sed -i "s/app.is_labs: .*/app.is_labs: $IS_LABS/" app/config/parameters.yml'

script:
  - composer test

sudo: false

matrix:
  exclude:
    - php: 7.2
      env: IS_LABS=1

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-xtools"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
