parameters:
  deletion_counter:
    en.wikipedia.org:
      CSD: "WP:CSD"
      PROD: "WP:PROD"
      AFD: "Articles for deletion"
      TFD: "Templates for discussion"
      MFD: "Miscellany for deletion"