parameters:
  tools:
    # This is the order they will appear in the interface.
    - EditCounter
    - ArticleInfo
    - Pages
    - TopEdits
    - AutoEdits
    - CategoryEdits
    - AdminStats
    - AdminScore
    - EditSummary
    - RfX
    - RfXVote
    - Quote
    - SimpleEditCounter
