monolog:
    channels: ['rate_limit', 'blacklist', 'crawler']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
        console:
            type:   console
            channels: ['!event', '!doctrine']
        rate_limit:
            # log all messages (since debug is the lowest level)
            level: info
            type: stream
            path: '%kernel.logs_dir%/rate_limit.log'
            channels: ['rate_limit']
        blacklist:
            # log all messages (since debug is the lowest level)
            level: info
            type: stream
            path: '%kernel.logs_dir%/blacklist.log'
            channels: ['blacklist']
        crawler:
            level: info
            type: stream
            path: '%kernel.logs_dir%/crawler.log'
            channels: ['crawler']

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
